services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: ninja-core
    container_name: ninjagl-core
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./backend:/app/backend
      - ./.storybook:/app/.storybook
      - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules: